apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "aml.fullname" . }}
  labels:
    app: {{ template "aml.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "aml.fullname" . }}
  template:
    metadata:
        name: {{ template "aml.fullname" . }}
        labels:
          app: {{ template "aml.fullname" . }}
          type: deployment 
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 6 }}
    {{- end -}}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ default .Chart.Name .Values.aml.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- if .Values.aml.env }}
        env:
{{ toYaml .Values.aml.env | indent 8 }}
    {{- else }}
        env:
        {{- if .Values.aml.environment }}
        - name: NODE_ENV
          value: {{ .Values.aml.environment }}
        {{- end -}}
    {{- end -}}
    {{- if .Values.aml.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.aml.livenessProbe | indent 10 }}
    {{- else }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/alive
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
    {{- end -}}
    {{- if .Values.aml.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.aml.readinessProbe | indent 10 }}
    {{- else }}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/alive
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
    {{- end -}}
    {{- if .Values.aml.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.aml.volumeMounts | indent 10 }}
    {{- else }}
        volumeMounts:
          - name: aml-config
            mountPath: {{ default "/target/Config" .Values.aml.amlconfig }}
            readOnly: true 
    {{- end }}
    {{- if .Values.aml.containerports }}
        ports:
{{ toYaml .Values.aml.containerports | indent 9 }}  
    {{- else }}    
        ports:
          - name: aml-https
            containerPort: 8443
            protocol: TCP 
          - name: aml-http
            containerPort: 8080
            protocol: TCP
    {{- end }}
    {{- if .Values.aml.volumes }}
      volumes:
{{ toYaml .Values.aml.volumes | indent 8 }}
    {{- else }}
      volumes:
        - name: aml-config
          configMap:
            name: {{ template "aml.fullname" . }}-config
            defaultMode: 420
    {{- end }}
    